const musicScript = document.createElement('script');
musicScript.src = '../Music/music.js';
document.head.appendChild(musicScript);
const themeButton = document.querySelector('.theme-toggle');
document.querySelectorAll('a[href]').forEach((link) => { link.addEventListener('click', (event) => { const target = link.getAttribute('href'); if (!target || target.startsWith('#') || link.target === '_blank') return; event.preventDefault(); document.body.classList.add('is-leaving'); window.setTimeout(() => { window.location.href = target; }, 280); }); });
document.body.classList.toggle('dark', localStorage.getItem('bean-theme') === 'dark');
themeButton.addEventListener('click', () => { const dark = document.body.classList.toggle('dark'); localStorage.setItem('bean-theme', dark ? 'dark' : 'light'); themeButton.textContent = dark ? '☀' : '☾'; });
let cart = JSON.parse(localStorage.getItem('bean-cart') || '[]');
const itemsElement = document.querySelector('#orderItems');
function renderCart() { itemsElement.innerHTML = ''; let total = 0; document.querySelector('#emptyMessage').hidden = cart.length > 0; cart.forEach((item, index) => { total += item.price * item.quantity; const row = document.createElement('article'); row.className = 'order-item'; row.innerHTML = `<div><h3>${item.name}</h3><label>Size <select data-field="size" data-index="${index}"><option ${item.size === 'Regular' ? 'selected' : ''}>Regular</option><option ${item.size === 'Large' ? 'selected' : ''}>Large</option></select></label><label>Sugar <select data-field="sugar" data-index="${index}"><option ${item.sugar === 'None' ? 'selected' : ''}>None</option><option ${item.sugar === 'Less' ? 'selected' : ''}>Less</option><option ${item.sugar === 'Normal' ? 'selected' : ''}>Normal</option><option ${item.sugar === 'Extra' ? 'selected' : ''}>Extra</option></select></label><label>Milk <select data-field="milk" data-index="${index}"><option ${item.milk === 'Whole milk' ? 'selected' : ''}>Whole milk</option><option ${item.milk === 'Oat milk' ? 'selected' : ''}>Oat milk</option><option ${item.milk === 'Almond milk' ? 'selected' : ''}>Almond milk</option></select></label></div><div class="item-controls"><button type="button" data-action="minus" data-index="${index}">−</button><strong>${item.quantity}</strong><button type="button" data-action="plus" data-index="${index}">+</button></div>`; itemsElement.appendChild(row); }); document.querySelector('#totalAmount').textContent = `$${total.toFixed(2)}`; }
itemsElement.addEventListener('click', (event) => { const button = event.target.closest('button'); if (!button) return; const item = cart[button.dataset.index]; item.quantity += button.dataset.action === 'plus' ? 1 : -1; if (item.quantity < 1) cart.splice(button.dataset.index, 1); localStorage.setItem('bean-cart', JSON.stringify(cart)); renderCart(); });
itemsElement.addEventListener('change', (event) => { const select = event.target.closest('select'); if (!select) return; cart[select.dataset.index][select.dataset.field] = select.value; localStorage.setItem('bean-cart', JSON.stringify(cart)); });
document.querySelector('#checkoutForm').addEventListener('submit', (event) => { event.preventDefault(); if (!event.target.reportValidity()) return; if (!cart.length) { document.querySelector('#orderStatus').textContent = 'Add a coffee before placing your order.'; return; } const paymentMethod = document.querySelector('#paymentMethod').value; document.querySelector('#orderStatus').textContent = `Order received. Payment: ${paymentMethod}. See you at the bar!`; cart = []; localStorage.setItem('bean-cart', '[]'); renderCart(); event.target.reset(); }); renderCart();